### ISSUE TITLE
Error X11 forwarding in Putty

### ISSUE THREAD

**Issue by vincentARM** [sakaki-/raspbian-nspawn-64#10]
Hello.
In 32 bits, create X11 windows is OK.
In container 64 bits , i have a error message :
pi@debian-buster-64:~/asm64/projet_X11 $ creatfen641
PuTTY X11 proxy: Unsupported authorisation protocol

Do you have a correction for this error ?
thanck you.

**Comment by sakaki-** [comment]
Perhaps look at:
https://superuser.com/questions/1125543/putty-x11-forwarding-unsupported-authorisation-protocol/1350167#1350167

**Comment by vincentARM** [comment]
Hello.
 Config file is ok in buster 32bits.
but in container 64 bits error is :
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-11-21 15:13:54 CET; 51ms ago
     Docs: man:sshd(8)
           man:sshd_config(5)
  Process: 809 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=0/SUCCESS)
  Process: 810 ExecStart=/usr/sbin/sshd -D $SSHD_OPTS (code=exited, status=255/EXCEPTION)
 Main PID: 810 (code=exited, status=255/EXCEPTION)

nov. 21 15:13:54 debian-buster-64 systemd[1]: Starting OpenBSD Secure Shell server...
nov. 21 15:13:54 debian-buster-64 sshd[810]: error: Bind to port 22 on 0.0.0.0 failed: Address already in use.
nov. 21 15:13:54 debian-buster-64 sshd[810]: error: Bind to port 22 on :: failed: Address already in use.
nov. 21 15:13:54 debian-buster-64 sshd[810]: fatal: Cannot bind any address.

I am not competent to solve this problem because I already lost all the connections with the raspberry while trying to modify the file of configuration.

**Comment by sakaki-** [comment]
The way things are set up, both container and host share the same networking subsystem (for convenience).

What is happening is that you already have an `sshd` server in the host (outer, 32-bit, Raspbian) system running, and this is bound to port 22 (the default).

When you try to start _another_ `sshd` in the guest (inner, 64-bit, Debian) container, it (by default) also tries to bind to port 22, finds this port is already in use, and exits.

To work around this, simply edit `/etc/ssh/sshd_config` in the guest (using `nano` or similar) and then uncomment and change the `Port` directive (to use, say, `Port 8022`). Then start the service, and direct your `ssh` client to that port.

**Comment by vincentARM** [comment]
Oh yes. It is Ok with changing port.
thanck you very much.

**Comment by sakaki-** [comment]
Glad to hear it is working for you now ^-^
Closing.
