### ISSUE TITLE
Breaks Bluetooth Headset

### ISSUE THREAD

**Issue by lr1729** [sakaki-/raspbian-nspawn-64#14]
I installed this on a few pi's and found that my bluetooth headset refused to play audio after. I re-flashed one before and after I installed it via apt, and found that after installing I was unable to play audio to a bluetooth headset. Using apt remove didn't seem to fix it

**Comment by sakaki-** [comment]
The userland is basically vanilla 32-bit Raspbian, so unless one of the additional dependencies (`pulseaudio`?) has caused the issue, any problems are likely to be with the shift to the (official) 64-bit kernel that the package requires.

Try using `sudo apt-get remove -y raspbian-nspawn-64 debian-buster-64` followed by `sudo apt-get -y autoremove` to uninstall any userland deps, and reboot. If you are then still having problems, comment out `arm_64bit=1` in `/boot/config.txt` and reboot.

If the latter step fixes it, there would appear to be a problem using your headset under the 64-bit kernel, and you should probably post a report to that effect on [this thread](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=250730) (in this case, it is not to do with `raspbian-nspawn-64` as such).

hth, sakaki

**Comment by lr1729** [comment]
Using `sudo apt-get remove -y raspbian-nspawn-64 debian-buster-64` and turning off the arm_64bit didn't fix it for me, bluetooth was able to connect and pair to the headphones properly, but I was unable to get it to play audio, which was the same situation as with nspawn-64 installed.

**Comment by sakaki-** [comment]
Just to double check, you did the `sudo apt-get -y autoremove` step + reboot also?

**Comment by lr1729** [comment]
Yep. I found that running `sudo apt remove pulseaudio` after uninstalling and removing `raspbian-nspawn-64 debian-buster-64` fixes it, but removing pulseaudio while nspawn-64 is installed causes the bluetooth icon to dissapear from the taskbar and running `bluetoothctl` hangs in the terminal.

**Comment by lr1729** [comment]
Would it be possible to disable the pulseaudio and bluetooth in nspawn-64 but still run 64 bit programs?
