### ISSUE TITLE
ds64-shell do not run

### ISSUE THREAD

**Issue by vincentARM** [sakaki-/raspbian-nspawn-64#15]
Hello.
i have a problèm to run ds64-shell since yesterday:
pi@raspberrypi:/var/run $ ds64-shell
Failed to get shell PTY: Connexion terminée par expiration du délai d'attente

I look the log to /var/lib/machines/debian-buster-64/var/log/auth.log :

May 18 15:35:27 debian-buster-64 systemd-logind[115]: Failed to read /var/run/ut
mp, ignoring: No such file or directory

I copy the file /run/utmp to /var/lib/machines/debian-buster-64/run/utmp 
but the problem is still there and I don't know what to do anymore.
Thanck you for you help.

**Comment by sakaki-** [comment]
This sometimes happens with `private-users` turned on. Have you by any chance changed `/etc/systemd/nspawn/debian-buster-64.nspawn`?

**Comment by vincentARM** [comment]
Hello.
No, I did not touch this file. Here is its content.
Maybe you have to delete the package raspbian-nspawn-64 and reinstall it?
Thanck you

[Exec]
PrivateUsers=no
Capability=CAP_NET_ADMIN

[Files]
Bind=/home
Bind=/lib/modules
Bind=/run/user:/run/host-user/
BindReadOnly=/etc/resolv.conf

[Network]
Private=no
VirtualEthernet=no

**Comment by sakaki-** [comment]
Try the following from the 32-bit console:

```console
pi@raspberrypi:~ $ ds64-stop
pi@raspberrypi:~ $ sudo cp -ax /var/lib/machines/debian-buster-64 /home/pi/debian-buster-64.bkp
pi@raspberrypi:~ $ sudo apt-get -y purge debian-buster-64
pi@raspberrypi:~ $ sudo apt-get -y install raspbian-nspawn-64
```

This should uninstall yoiur current Debian Buster image (leaving a copy in `/home/pi/debian-buster-64.bkp/...`, in case there is any work in there you need to keep) and the host-side support package, and then re-install fresh copies of both. Hopefully all will then work again.

best, sakaki

**Comment by vincentARM** [comment]
Hello. 
I followed your advice by carrying out the operations above and everything is ok now.
Thank you so much.

**Comment by vincentARM** [comment]
After reflection, I suspect the use of the functions of the 64-bit openssl library from the 64-bit ARM assembler.
This will degrade the operation of the container.
Have a good day.
