### ISSUE TITLE
Can't change the hostname of the container via standard settings and/or commands

### ISSUE THREAD

**Issue by 2072** [sakaki-/raspbian-nspawn-64#17]
Hello,

Thanks for raspbian-nspawn-64. I'm using it on a headless server.

The default name `debian-buster-64` doesn't suit my needs (it would have had if it had simply been named 'ORIGINALHOST-64')

I've renamed the machine via the `machinectl` command, I've also tried `hostnamectl --set-hostname` inside the container, but after a stop-start of the machine, it reverts back to 'debian-buster-64'. I've also tried setting the Hostname option in the `/etc/systemd/nspawn/NEWNAME.nspawn` file but it has, like the rest no effect...
I even tried modifying the systemd service file and add a `--hostname=%i` still with no effect.

So where does this `debian-buster-64` comes from???  (I'm currently running a rgrep on my whole file system to find it...)

ok my rgrep paid off just when I was about to submit this issue... I needed to edit the file `/etc/given-hostname` inside the container. This should be added somewhere in the documentation to save others some of their time. (it took me 2 hours to find this...)

**Comment by sakaki-** [comment]
@2072 -
thanks, done.
Best, sakaki
