### ISSUE TITLE
Buster host?

### ISSUE THREAD

**Issue by sigboe** [sakaki-/raspbian-nspawn-64#2]
Would you please look into updating to the buster host image?

**Comment by sakaki-** [comment]
This is on my list to do, once the Pi4-compatible 64-bit Gentoo image is shipped.
ETA about 4 to 6 weeks therefore.
Best, sakaki

**Comment by r3f** [comment]
Is there a release date of rasbian-busterr-nspawn for pi4?

**Comment by sakaki-** [comment]
I'm hoping to ship a v1.5.1 bugfix release of the [gentoo-on-rpi-64bit](https://github.com/sakaki-/gentoo-on-rpi-64bit) image this weekend, which should hopefully stabilize the RPi4-compatibility introduced in v1.50.

Updating this nspawn image is next up on my todo list after that. So should be out within a fortnight or so, if all goes well.

**Comment by r3f** [comment]
look forward to your work , its really nice .

**Comment by sakaki-** [comment]
OK, so this appears to be basically running now on Buster / RPi4.
Packaging and further test next week, then release ^-^

Best, sakaki

**Comment by sakaki-** [comment]
v1.3.0 just released, with RPi4 support / Raspbian Buster host OS / official 64-bit kernel.
Enjoy ^-^
Best, sakaki
