### ISSUE TITLE
Variable Path

### ISSUE THREAD

**Issue by vincentARM** [sakaki-/raspbian-nspawn-64#7]
Thank you for this release Linux 64 bits. It works great on my raspberry pi 3b+
How to change the PATH variable in the 64-bit container ?
I modified the .profile but the modification is only taken into account for the 3rd bits. Thank you.
Sorry for my english, is french traduction with google.

**Comment by sakaki-** [comment]
When you have a 64-bit shell open, you can just export `PATH` directly, but if you want to change it up front, edit the files `/usr/bin/ds64-run` and `/usr/bin/ds64-shell` on the host (32-bit) system, [here](https://github.com/sakaki-/raspbian-nspawn-64/blob/9b03f2e9c179b2795883038946ec9259aeb773d0/host-image/usr/bin/ds64-run#L35) and [here](https://github.com/sakaki-/raspbian-nspawn-64/blob/9b03f2e9c179b2795883038946ec9259aeb773d0/host-image/usr/bin/ds64-shell#L32).

**Comment by vincentARM** [comment]
It is OK.  Thank you. 
Now i write program in assembly arm 64 bits.
good night.

**Comment by sakaki-** [comment]
Closing this now. Please re-open if you experience further issues on this topic.
