### ISSUE TITLE
Sorry i have make a error.

### ISSUE THREAD

**Issue by vincentARM** [sakaki-/raspbian-nspawn-64#9]
Following the last modification, I had to make an error because the 64-bit container directories are no longer identical. I can not see the directory / home / pi anymore. How to correct? Thank you again for your help and patience.

Last login: Sun Nov 10 15:03:16 2019
pi @ raspberrypi: ~ $ ls
asm C Documents listing.txt Public templates Downloads
asm64 Desktop Images MagPi Music scripts Videos
pi @ raspberrypi: ~ $ ds64-shell
Connected to debian-buster-64 machine. Press ^] three times within 1s to exit session.
pi @ debian-buster-64: / $ ls
bin dev home media opt root sbin sys usr
boot etc lib mnt proc run srv tmp var
ft @ debian-buster-64: / $

**Comment by vincentARM** [comment]
Delete the message. I find my error and container 64 is now OK.

**Comment by sakaki-** [comment]
OK, thanks for letting me know. Closing now.
